#!/usr/bin/env python3
"""Determine if a number is prime."""
import sys


def is_prime(n: int) -> bool:
    """Return True if n is a prime number."""
    if n <= 1:
        return False
    if n <= 3:
        return True
    if n % 2 == 0 or n % 3 == 0:
        return False
    i = 5
    while i * i <= n:
        if n % i == 0 or n % (i + 2) == 0:
            return False
        i += 6
    return True


def main():
    if len(sys.argv) != 2:
        print("Usage: Primenumbers <number>")
        return
    try:
        num = int(sys.argv[1])
    except ValueError:
        print("Please provide an integer.")
        return
    if is_prime(num):
        print(f"{num} is prime")
    else:
        print(f"{num} is not prime")


if __name__ == "__main__":
    main()
